export const workContent = [
  {
    projectName: 'Starstell',
    projectType: 'WEB & APP DEVELOPMENT',
    projectUrl: '/case-study/starstell',
    filterTags: 'app-dev sass',
    projectThumb: '/img/starstell-thumb.webp',
  },
  {
    projectName: 'Magicfinserv',
    projectType: 'E-COMMERCE PLATFORM DEVELOPEMENT',
    projectUrl: '/case-study/magicfinserv',
    filterTags: 'cms infra',
    projectThumb: '/img/magicfinserv-thumb.webp',
  },
  {
    projectName: 'Vimal Wires & Cable',
    projectType: 'ERP SYSTEM',
    projectUrl: '/case-study/vimal-wires-and-cable',
    filterTags: 'app-dev e-comm',
    projectThumb: '/img/vimal-cables-thumb.webp',
  },
  {
    projectName: 'Skydo',
    projectType: 'FINTECH | APP + WEB + ADMIN',
    projectUrl: '/case-study/skydo',
    filterTags: 'app-dev fintech',
    projectThumb: '/img/cs/skydo/Skydo1.png',
  },
  {
    projectName: 'Fampay',
    projectType: 'FINTECH | APP + WEB + ADMIN',
    projectUrl: '/case-study/famapp',
    filterTags: 'app-dev fintech',
    projectThumb: '/img/cs/famapp/famapp4.png',
  },
  {
    projectName: 'StockGro',
    projectType: 'FINTECH | APP + WEB',
    projectUrl: '/case-study/stockgro',
    filterTags: 'app-dev fintech',
    projectThumb: '/img/cs/stockgro/stockgro1.png',
  },
  {
    projectName: 'Zeller',
    projectType: 'FINTECH | APP + WEB',
    projectUrl: '/case-study/myzeller',
    filterTags: 'app-dev fintech',
    projectThumb: '/img/cs/myzelller/myzeller5.png',
  },
  {
    projectName: 'Airwallex',
    projectType: 'FINTECH | APP + WEB',
    projectUrl: '/case-study/airwallex',
    filterTags: 'app-dev fintech',
    projectThumb: '/img/cs/airwallex/AirWallex4.png',
  },
  {
    projectName: 'Soldo',
    projectType: 'FINTECH | APP + WEB',
    projectUrl: '/case-study/soldo',
    filterTags: 'app-dev fintech',
    projectThumb: '/img/cs/soldo/soldo.png',
  },
  {
    projectName: 'Yonder',
    projectType: 'FINTECH | APP + WEB',
    projectUrl: '/case-study/yonder',
    filterTags: 'app-dev fintech',
    projectThumb: '/img/cs/yonder/yonder2.png',
  },
  {
    projectName: 'Lunar',
    projectType: 'DIGITAL BANKING | APP + WEB',
    projectUrl: '/case-study/lunar',
    filterTags: 'app-dev fintech',
    projectThumb: '/img/cs/lunar/luner1.png',
  },
  {
    projectName: 'Graphy',
    projectType: 'EDTECH | APP + WEB',
    projectUrl: '/case-study/graphy',
    filterTags: 'app-dev edtech',
    projectThumb: '/img/cs/graphy/graphy1.png',
  },
  {
    projectName: 'EdTech Hub',
    projectType: 'EDTECH | APP + WEB',
    projectUrl: '/case-study/edtechhub',
    filterTags: 'app-dev edtech',
    projectThumb: '/img/cs/edtechhub/edtechhub2.png',
  },
  {
    projectName: 'Testbook',
    projectType: 'EDTECH | APP + WEB',
    projectUrl: '/case-study/testbook',
    filterTags: 'app-dev edtech',
    projectThumb: '/img/cs/testbook/testbook1.png',
  },
  {
    projectName: 'Teachmint',
    projectType: 'EDTECH | APP + WEB',
    projectUrl: '/case-study/teachmint',
    filterTags: 'app-dev edtech',
    projectThumb: '/img/cs/teachmint/teachmint.png',
  },
  {
    projectName: 'Sunstone',
    projectType: 'EDTECH | APP + WEB',
    projectUrl: '/case-study/sunstone',
    filterTags: 'app-dev edtech',
    projectThumb: '/img/cs/sunstone/sunstone1.png',
  },
  {
    projectName: 'Learnosity',
    projectType: 'EDTECH | WEB',
    projectUrl: '/case-study/learnosity',
    filterTags: 'app-dev edtech',
    projectThumb: '/img/cs/learnosity/learnosity2.png',
  },
  {
    projectName: 'Cluey Learning',
    projectType: 'EDTECH | APP + WEB',
    projectUrl: '/case-study/clueylearning',
    filterTags: 'app-dev edtech',
    projectThumb: '/img/cs/clueylearning/clueylearning1.png',
  },
  {
    projectName: 'Seneca Learning',
    projectType: 'EDTECH | APP + WEB',
    projectUrl: '/case-study/senecalearning',
    filterTags: 'app-dev edtech',
    projectThumb: '/img/cs/senecalearning/senecalearning1.png',
  },
  {
    projectName: 'Snitch',
    projectType: 'E-COMMERCE | APP + WEB + ADMIN',
    projectUrl: '/case-study/snitch',
    filterTags: 'app-dev e-comm',
    projectThumb: '/img/cs/snitch/snitch1.png',
  },
    {
    projectName: 'Number Dekho',
    projectType: 'WEB & APP DEVELOPMENT',
    projectUrl: '/case-study/numberdekho',
    filterTags: 'app-dev e-comm',
    projectThumb: '/img/numberdekho.webp',
  },
    {
    projectName: 'Broopi',
    projectType: 'WEB & APP DEVELOPMENT',
    projectUrl: '/case-study/broopi',
    filterTags: 'sass cms',
    projectThumb: '/img/broopi-thumb.webp',
  },
    {
    projectName: 'Milanoa',
    projectType: 'WEB DEVELOPMENT',
    projectUrl: '/case-study/milanoa',
    filterTags: 'infra sass',
    projectThumb: '/img/milanoa-thumb.webp',
  },
];
